from __future__ import annotations

from enum import StrEnum


class FathomEvent(StrEnum):
    """
    Telemetry events for Fathom execution.
    """

    REASONING = "REASONING"
    GROUNDING = "GROUNDING"
    PLANNED_ACTION = "PLANNED_ACTION"
    PLAN_SYNTHESIZED = "PLAN_SYNTHESIZED"

    STEP_AUDITED = "STEP_AUDITED"
    STEP_COMPLETED = "STEP_COMPLETED"
    SCRIPT_GENERATED = "SCRIPT_GENERATED"
    SCRIPT_GENERATION_FAILED = "SCRIPT_GENERATION_FAILED"

    PROMPT_BUILT = "PROMPT_BUILT"
    CONTEXT_CAPTURED = "CONTEXT_CAPTURED"

    PHASE_HEARTBEAT = "PHASE_HEARTBEAT"
    LLM_CALL_COMPLETED = "LLM_CALL_COMPLETED"

    HITL_RECEIVED = "HITL_RECEIVED"
    HITL_REQUESTED = "HITL_REQUESTED"

    WORKFLOW_FAILED = "WORKFLOW_FAILED"
    WORKFLOW_PAUSED = "WORKFLOW_PAUSED"
    WORKFLOW_RESUMED = "WORKFLOW_RESUMED"
    RECORDER_DISABLED = "RECORDER_DISABLED"

    WORKFLOW_CANCELLED = "WORKFLOW_CANCELLED"
    WORKFLOW_COMPLETED = "WORKFLOW_COMPLETED"

    INTENT_REJECTED = "INTENT_REJECTED"
    INTENT_QUALIFIED = "INTENT_QUALIFIED"
    INTENT_QUALIFYING = "INTENT_QUALIFYING"
    INTENT_DECOMPOSING = "INTENT_DECOMPOSING"

    SLOW_QUERY = "SLOW_QUERY"
