from __future__ import annotations

from enum import StrEnum


class FathomEvent(StrEnum):
    """
    Telemetry events for Fathom execution.
    """

    REASONING = "REASONING"
    PLANNED_ACTION = "PLANNED_ACTION"
    STEP_COMPLETED = "STEP_COMPLETED"
    STEP_AUDITED = "STEP_AUDITED"
    SCRIPT_GENERATED = "SCRIPT_GENERATED"
    PROMPT_BUILT = "PROMPT_BUILT"
    CONTEXT_CAPTURED = "CONTEXT_CAPTURED"

    HITL_RECEIVED = "HITL_RECEIVED"
    HITL_REQUESTED = "HITL_REQUESTED"

    WORKFLOW_PAUSED = "WORKFLOW_PAUSED"
    WORKFLOW_RESUMED = "WORKFLOW_RESUMED"

    WORKFLOW_CANCELLED = "WORKFLOW_CANCELLED"
    WORKFLOW_COMPLETED = "WORKFLOW_COMPLETED"
