from __future__ import annotations

from typing import Final

DEFAULT_LOCALIZATION_BUDGET: Final[int] = 120
DEFAULT_OCR_PERCEPTION_BUDGET: Final[int] = 800
DEFAULT_LOCAL_PERCEPTION_BUDGET: Final[int] = 120
DEFAULT_LOCALIZATION_CONFIDENCE_THRESHOLD: Final[float] = 0.72

DEFAULT_HEALING_RUN_BUDGET: Final[int] = 5
DEFAULT_HEALING_TASK_BUDGET: Final[int] = 2
DEFAULT_PAID_LOCALIZATION_ATTEMPT_BUDGET: Final[int] = 0

DEFAULT_LOOP_THRESHOLD: Final[int] = 3
DEFAULT_LOOP_WINDOW: Final[int] = 10
DEFAULT_MAX_STEPS: Final[int] = 20
DEFAULT_REALIGNMENT_BUDGET: Final[int] = 3
DEFAULT_CONTEXT_WINDOW: Final[int] = 10
