from __future__ import annotations

from fathom.constants.execution import VISUAL_HASH_LENGTH

ZERO_HASH: str = "0" * VISUAL_HASH_LENGTH

MAX_VISUAL_HASH_DISTANCE: int = 64
DEFAULT_SAME_SCREEN_THRESHOLD: int = 8

SIGNATURE_TEXT_PREVIEW_LENGTH: int = 32
SIGNATURE_VALUE_PREVIEW_LENGTH: int = 16

BOUNDS_DIGEST_LENGTH: int = 6
INTERACTION_TEXT_PREVIEW_LENGTH: int = 30

ACTION_EFFECT_SSIM_THRESHOLD: float = 0.98
ACTION_EFFECT_PHASH_DISTANCE_THRESHOLD: int = 4
ACTION_EFFECT_SCROLL_DISTANCE_THRESHOLD_PX: float = 5.0
ACTION_EFFECT_CONTENT_DIFF_RATIO_THRESHOLD: float = 0.005

ACTIVITY_CHANGED_SIGNAL_WEIGHT: int = 2
XML_HASH_CHANGED_SIGNAL_WEIGHT: int = 2
INTERACTION_HASH_CHANGED_SIGNAL_WEIGHT: int = 1

SSIM_CHANGED_SIGNAL_WEIGHT: int = 1
PHASH_CHANGED_SIGNAL_WEIGHT: int = 1

CONTENT_DIFF_SIGNAL_WEIGHT: int = 1
SCROLL_CHANGED_SIGNAL_WEIGHT: int = 1

MEANINGFUL_STATE_SSIM_THRESHOLD: float = 0.95
MEANINGFUL_STATE_SIGNAL_WEIGHT_THRESHOLD: int = 2
MEANINGFUL_STATE_PHASH_DISTANCE_THRESHOLD: int = 8
MEANINGFUL_STATE_CONTENT_DIFF_RATIO_THRESHOLD: float = 0.05
MEANINGFUL_STATE_SCROLL_DISTANCE_THRESHOLD_PX: float = 30.0

LOOP_OSCILLATION_AB_WINDOW: int = 4
LOOP_OSCILLATION_ABC_WINDOW: int = 6
LOOP_SCROLL_STALL_MIN_STREAK: int = 7
LOOP_SCROLL_STALL_DISTANCE_THRESHOLD: int = 4
LOOP_ACTION_VELOCITY_INTERVAL_THRESHOLD_SECONDS: float = 1.5

STATUS_BAR_HEIGHT_PX: int = 80
NAVIGATION_BAR_HEIGHT_PX: int = 60

PIXEL_CHANGE_THRESHOLD: int = 15
MIN_CHANGED_REGION_AREA_PX: int = 100

DILATION_ITERATIONS: int = 2
DILATION_KERNEL_SIZE: int = 10

SSIM_K1: float = 0.01
SSIM_K2: float = 0.03
SSIM_GAUSSIAN_SIGMA: float = 1.5
SSIM_GAUSSIAN_KERNEL_SIZE: int = 11
