"""Backward-compatible re-export. Canonical location: fathom.constants.prompts."""

from fathom.constants.prompts import (
    ACTION_RULES,
    COMMON_RULES,
    CONFIDENCE_RULES,
    COORD_RULES,
    PRECISION_RULES,
    STUCK_PROMPT,
    SUBGOAL_VERIFICATION_SYSTEM,
    SUBGOAL_VERIFICATION_USER_TEMPLATE,
    TOOL_GUIDANCE,
    UI_RULES,
    VALIDATION_SUBJECT_EXTRACTION_SYSTEM,
    VALIDATION_SUBJECT_EXTRACTION_USER,
    VERIFICATION_SYSTEM,
    VERIFICATION_USER_TEMPLATE,
)

__all__ = [
    "ACTION_RULES",
    "COMMON_RULES",
    "CONFIDENCE_RULES",
    "COORD_RULES",
    "PRECISION_RULES",
    "STUCK_PROMPT",
    "SUBGOAL_VERIFICATION_SYSTEM",
    "SUBGOAL_VERIFICATION_USER_TEMPLATE",
    "TOOL_GUIDANCE",
    "UI_RULES",
    "VALIDATION_SUBJECT_EXTRACTION_SYSTEM",
    "VALIDATION_SUBJECT_EXTRACTION_USER",
    "VERIFICATION_SYSTEM",
    "VERIFICATION_USER_TEMPLATE",
]
